### ISSUE TITLE
Luasec-0.6.1 fails to build with luarocks

### ISSUE THREAD

**Issue by comfix** [brunoos/luasec#101]
Luasec fails to build as mentioned.
Using Arch with OpenSSL (1.1.0e)
`
Warning: falling back to curl - install luasec to get native HTTPS support
Installing https://luarocks.org/luasec-0.6-1.rockspec
Klone nach 'luasec' ...
remote: Counting objects: 116, done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 116 (delta 33), reused 76 (delta 22), pack-reused 0
Empfange Objekte: 100% (116/116), 68.52 KiB | 0 bytes/s, Fertig.
Löse Unterschiede auf: 100% (33/33), Fertig.
Hinweis: Checke '20443861ebc3f6498ee7d9c70fbdaa059bec15e1' aus.

<< GIT WARNING....>>

gcc -O2 -fPIC -I/usr/include -c src/x509.c -o src/x509.o -I/usr/include -Isrc/ -Isrc/luasocket
src/x509.c: In Funktion »push_asn1_string«:
src/x509.c:149:5: Warnung: »ASN1_STRING_data« ist veraltet [-Wdeprecated-declarations]
     lua_pushlstring(L, (char*)ASN1_STRING_data(string),
     ^~~~~~~~~~~~~~~
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from src/x509.c:22:
/usr/include/openssl/asn1.h:553:1: Anmerkung: hier deklariert
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
src/x509.c: In Funktion »push_asn1_ip«:
src/x509.c:185:3: Warnung: »ASN1_STRING_data« ist veraltet [-Wdeprecated-declarations]
   unsigned char *ip = ASN1_STRING_data(string);
   ^~~~~~~~
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from src/x509.c:22:
/usr/include/openssl/asn1.h:553:1: Anmerkung: hier deklariert
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
src/x509.c: In Funktion »meth_extensions«:
src/x509.c:296:35: Fehler: dereferencing pointer to incomplete type »X509_EXTENSION {aka struct X509_extension_st}«
     push_asn1_objname(L, extension->object, 1);
                                   ^~
src/x509.c: In Funktion »meth_pubkey«:
src/x509.c:407:32: Fehler: dereferencing pointer to incomplete type »EVP_PKEY {aka struct evp_pkey_st}«
       switch(EVP_PKEY_type(pkey->type)) {
                                ^~

Error: Build error: Failed compiling object src/x509.o
`

**Comment by tpimh** [comment]
I get similar error with OpenSSL 1.1.0f.

**Comment by limadm** [comment]
Hello, the rockspec in luarocks.org is not updated yet.
Could you try to clone the repo and install from it?
```
git clone https://github.com/limadm/luasec.git
cd luasec
luarocks make luasec-0.6-1.rockspec
```
Please report your results, thanks. :)

**Comment by comfix** [comment]
Works just fine! Compilation without any mayor errors just some outdated function warnings.
Thanks a lot!

**Comment by spacekookie** [comment]
When can we expect the package to be updated then? Because it's kinda annoying not being able to install via `luarocks install luasec` :/

**Comment by CapacitorSet** [comment]
I pushed the fixes to a fork, and published them as [`luasec-fixed`](http://luarocks.org/modules/CapacitorSet/luasec-fixed). You can install it with `luarocks install luasec-fixed`.

**Comment by spacekookie** [comment]
Have the maintainers seriously not managed to update their package in over two months? Seriously...it's not that hard -_-

**Comment by Tieske** [comment]
something like this should also work;
```
luarocks install https://raw.githubusercontent.com/brunoos/luasec/master/luasec-0.6-1.rockspec
```

I don't like adding temp stuff in package repositories.

**Comment by limadm** [comment]
Hi, guys! I contacted @brunoos and he will update the repository soon to the version 0.7 with this patch. Stay tuned!

**Comment by brunoos** [comment]
0.7alpha is out... since I'm not sure about some names and I have to test it in some platforms (mainly Windows).
