### ISSUE TITLE
Unidentified bug on Ubuntu 16.04

### ISSUE THREAD

**Issue by x2592** [brunoos/luasec#107]
While installing/configuring Prosody to integrate with diaspora*, as per this page:

https://wiki.debian.org/Diaspora/XMPP

I am running into the problem reported here:

https://sourceforge.net/p/luarocks/mailman/message/35354010/

Command line output under Ubuntu 16.04:

root@somewhere ~ # luarocks install bcrypt

Error: LuaRocks 2.2.0 bug (please report at luarocks-developers@lists.sourceforge.net).
/usr/share/lua/5.1/ssl.lua:125: bad argument #1 to 'setfd' (number expected, got nil)
stack traceback:
	[C]: in function 'request'
	/usr/share/lua/5.1/ssl/https.lua:133: in function 'request'
	/usr/share/lua/5.1/luarocks/fs/lua.lua:557: in function 'request'
	/usr/share/lua/5.1/luarocks/fs/lua.lua:621: in function 'http_request'
	/usr/share/lua/5.1/luarocks/fs/lua.lua:659: in function 'download'
	/usr/share/lua/5.1/luarocks/fetch.lua:40: in function 'fetch_url'
	/usr/share/lua/5.1/luarocks/manif.lua:97: in function 'fetch_manifest_from'
	/usr/share/lua/5.1/luarocks/manif.lua:135: in function 'load_manifest'
	/usr/share/lua/5.1/luarocks/search.lua:175: in function 'manifest_search'
	/usr/share/lua/5.1/luarocks/search.lua:208: in function 'search_repos'
	/usr/share/lua/5.1/luarocks/search.lua:284: in function 'find_suitable_rock'
	/usr/share/lua/5.1/luarocks/install.lua:146: in function </usr/share/lua/5.1/luarocks/install.lua:122>
	(tail call): ?
	[C]: in function 'xpcall'
	/usr/share/lua/5.1/luarocks/command_line.lua:208: in function 'run_command'
	/usr/bin/luarocks:33: in main chunk
	[C]: ?

Sorry I can't give you more details... Hope this helps. Feel free to contact me if I can be of any help to you.

**Comment by brunoos** [comment]
I got this error when there are 2 installation of luasec:

1) sudo apt-get install prosody
This will install luasec 0.5.1 from ubuntu repository as dependency (luasocket also).

2) sudo apt-get install luarocks

3) sudo luarocks install luasec 0.6-1
Now you have 2 versions of luasec on your system. (and 2 luasocket)

4) sudo luarocks install bcrypt
<error>

If you install only one version of luasec, there is no error.
But I do not know why the error is triggered.

**Comment by brunoos** [comment]
My guess is this line in /usr/bin/luarocks:

package.path = [[/usr/share/lua/5.1/?.lua;]]..package.path

--
This is the package search path:

brunoos@ubuntutemp:~$ lua -l blablabla
lua: module 'blablabla' not found:
	no field package.preload['blablabla']
	no file './blablabla.lua'
	no file '/usr/local/share/lua/5.1/blablabla.lua'
	no file '/usr/local/share/lua/5.1/blablabla/init.lua'
	no file '/usr/local/lib/lua/5.1/blablabla.lua'
	no file '/usr/local/lib/lua/5.1/blablabla/init.lua'
	no file '/usr/share/lua/5.1/blablabla.lua'
	no file '/usr/share/lua/5.1/blablabla/init.lua'
	no file './blablabla.so'
	no file '/usr/local/lib/lua/5.1/blablabla.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/blablabla.so'
	no file '/usr/lib/lua/5.1/blablabla.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

---
luarocks install luasec 0.6 in:
'/usr/local/share/lua/5.1/ssl.lua'
'/usr/local/lib/lua/5.1/ssl.so'

apt-get install luasec 0.5.1 in:
'/usr/share/lua/5.1/ssl.lua'
'/usr/lib/x86_64-linux-gnu/lua/5.1/ssl.so'

I think that when luarocks change package search path it loads 'ssl.lua' from 0.5.1 and 'ssl.so' from 0.6.
--

If I change /usr/bin/luarocks like this, it works:

--package.path = [[/usr/share/lua/5.1/?.lua;]]..package.path
package.path = [[/usr/local/share/lua/5.1/?.lua;/usr/share/lua/5.1/?.lua;]]..package.path
