### ISSUE TITLE
ssl settimeout is unuseful,call conn:receive will get resp with timeout 0

### ISSUE THREAD

**Issue by heshun25** [brunoos/luasec#109]
before call conn:receive , settimeout(1) and when i call the conn:receive,i had printf the value of tm->block  in method ssl_recv( *ctx,*data,count,got,tm) and tm->block is 1.000000 in file ssl.c,it's ok,also i printf the value of tm->block in method socket_waitfd(p_socket,sw,p_timeout) in file usocket.c and i found the value of tm->block had changed, so call poll with a error timeout value, maybe is a bug，i also printf the address of tm, all of the address is the same

**Comment by heshun25** [comment]
@brunoos can you help me? tks

**Comment by brunoos** [comment]
There was a problem with the rockspecs, it was missing some defines and it was affecting the timeout.

Can you give more information about you use and how do you installed luasec?
