### ISSUE TITLE
[Q] use only public luaSocket APIs

### ISSUE THREAD

**Issue by ildar** [brunoos/luasec#110]
Just a question: will luasec move to using public (Lua) APIs of luasocket? Is it at all possible?
Bringing a copy doesn't look elegant 🙁

**Comment by brunoos** [comment]
I have no intention of changing this for now.

**Comment by brunoos** [comment]
Ok, as far as I remember, I use luasocket code because I want to keep the same semantic. Since it does not export these functions, and I do not want to rewrite everything, I imported them. The files keep the original license and luasec informs that it use luasocket in VERSION variable.

**Comment by ildar** [comment]
then the followup question:
What will happen if the bundled version will not be the same as the version in `require "socket"`?
I.e. what will happen if they happen to be in the same address space?
