### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by kkkrackpot** [brunoos/luasec#111]
Hi,

I'm trying to make luasec-0.6 fetch json data:
```
local https = require("ssl.https")
local rbody, rcode, rhead, rstatus = https.request("https://www.zpool.ca/api/status")
print (rbody, rcode, rhead, rstatus)
```
It says `nil	sslv3 alert handshake failure	nil	nil`

However the URL works fine with Chromium or curl.

**Comment by brunoos** [comment]
luasec-0.6 does not set SNI.

Add this line to https.lua or use luasec-0.7alpha.
https://github.com/brunoos/luasec/blob/master/src/https.lua#L92
