### ISSUE TITLE
tlsv1 alert protocol version with lua copas test suite when built with libressl

### ISSUE THREAD

**Issue by ncopa** [brunoos/luasec#114]
lua copa tests suite fails to fetch things from https with lua sec on Alpine Linux, with libressl 2.7:
````
src/copas.lua:40: src/copas.lua:382: tlsv1 alert protocol version       thread: 0x5642b26b8800  SSL connection: 0x5642b26fad08
````
So it seems that fetching from `https://google.nl` is broken.

**Comment by brunoos** [comment]
Can you give some information how to reproduce it?
