### ISSUE TITLE
LuaSec 0.7 does not work with Openssl 1.1.0h

### ISSUE THREAD

**Issue by aryajur** [brunoos/luasec#118]
Hi,
    I compiled OpenSSL 1.1.0h and then LuaSec commit fdb2fa5f5991e1df0a0d61badb64cda67918ae95 [fdb2fa5f5991e1df0a0d61badb64cda67918ae95](https://github.com/brunoos/luasec/commit/fdb2fa5f5991e1df0a0d61badb64cda67918ae95) which is the latest right now. When I do require("ssl") I get the following error:

error loading module 'ssl.core' from file './ssl.so':
        ./ssl.so: undefined symbol: sk_free
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        ./ssl.lua:8: in main chunk
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: in ?

Without changing anything else I just compiled LuaSec0.6 and used that and it worked fine. I was trying to use LuaSec 0.7 but did not find any download link to it in the documentation page so just got the latest source code.

**Comment by ewestbrook** [comment]
I'm unable to [find](https://github.com/brunoos/luasec/search?q=sk_free&unscoped_q=sk_free) any reference at all to `sk_free` in `luasec`.

If your system's `openssl` is version `1.1.0` or later, [apparently](https://github.com/crystal-lang/crystal/pull/4230) some symbols including `sk_free` have changed to e.g. `OPENSSL_sk_free`.  I have not yet encountered that new version myself, and I'm not yet certain how it will affect `luasec`.

**Comment by brunoos** [comment]
You can find the link to 0.7 on Github releases.
I cannot see this issue right now...

**Comment by aryajur** [comment]
Thanks for the replies. I will try 0.7 from releases now. What is the OpenSSL version that is tested with LuaSec currently.

**Comment by pkulchenko** [comment]
I've tested with 1.0.2o without issues (was the latest at that time); haven't tried 1.1.x.

**Comment by aryajur** [comment]
Thank you for all the replies. Some updates from me.
   - Earlier it worked with LuaSec0.6 and OpenSSL1.1.0h but then when I tried again as a fresh installed it showed the same error. I don't know why.
    - So I installed LuaSec 0.7 from the releases and Installed OpenSSL 1.0.2o and that worked fine without problems.
