### ISSUE TITLE
Compile error with Visual Studio 2010

### ISSUE THREAD

**Issue by treahard** [brunoos/luasec#127]
In context.c:

const char *str = luaL_checkstring(L, 2);

SSL_CTX_set_options(ctx, SSL_OP_SINGLE_ECDH_USE);
  
EC_KEY *key = lsec_find_ec_key(L, str);

VS 2010 requires the definition of key to be before the set_options.
I changed it as follows:

  const char *str = luaL_checkstring(L, 2);
  EC_KEY *key = NULL;

  SSL_CTX_set_options(ctx, SSL_OP_SINGLE_ECDH_USE);

  key = lsec_find_ec_key(L, str);

**Comment by brunoos** [comment]
done
