### ISSUE TITLE
Remain (partially) ABI Compatible

### ISSUE THREAD

**Issue by daurnimator** [brunoos/luasec#13]
The changes to `t_context` will break other projects that try and interoperate with luasec.

E.g. https://github.com/chatid/fend/blob/master/ssl.lua#L10

If the ABI must change, ensure there is some (`dlsym`-able) way to check which version you're interoperating with.

**Comment by daurnimator** [comment]
Can you provide any assurance on the layout of `t_context`?

At least that the `SSL_CTX*` will remain the first element of the struct?

**Comment by brunoos** [comment]
I think it is possible keep it as first field.
But I want to be clear that I see t_context, t_ssl, etc., as internal structures.
If we need some kind of access to these structures, it would be saver to think in a standard C API to retrieve OpenSSL objects from LuaSec.

**Comment by daurnimator** [comment]
> If we need some kind of access to these structures, it would be saver to think in a standard C API to retrieve OpenSSL objects from LuaSec.

Ahha. I just noticed `lsec_checkcontext` exists.

**Comment by daurnimator** [comment]
Could you add a `lsec_testcontext` to go along with that?

**Comment by daurnimator** [comment]
@brunoos ?

**Comment by brunoos** [comment]
sorry, what is ``lsec_testcontext`` ?

**Comment by daurnimator** [comment]
> sorry, what is lsec_testcontext ?

Analogous to `luaL_testudata` vs `luaL_checkudata`.
It would test the argument to see if it's a valid context; if so, return a pointer to the `SSL_CTX`. if not, return `NULL`.

**Comment by brunoos** [comment]
ok... the easy way is use ```luaL_testudata```, but there is no such function in Lua 5.1.

It should be re-implemented (or imported from 5.2 or 5.3).

Do you think another way?

```
/*-- Compat - Lua 5.1 --------------------------------------------------------*/

#if (LUA_VERSION_NUM == 501)

#define luaL_testudata(L, ud, tname)  testudata(L, ud, tname)

static void *testudata (lua_State *L, int ud, const char *tname) {
  void *p = lua_touserdata(L, ud);
  if (p != NULL) {  /* value is a userdata? */
    if (lua_getmetatable(L, ud)) {  /* does it have a metatable? */
      luaL_getmetatable(L, tname);  /* get correct metatable */
      if (!lua_rawequal(L, -1, -2))  /* not the same? */
        p = NULL;  /* value is a userdata with wrong metatable */
      lua_pop(L, 2);  /* remove both metatables */
      return p;
    }
  }
  return NULL;  /* value is not a userdata with a metatable */
}

#endif
```

**Comment by daurnimator** [comment]
> the easy way is use luaL_testudata, but there is no such function in Lua 5.1.
> 
> It should be re-implemented (or imported from 5.2 or 5.3).

Ah, I didn't realise it was new in 5.2/5.3.

Your implementation looks fine, alternatively you could copy the implementation from: https://github.com/keplerproject/lua-compat-5.3/blob/master/c-api/compat-5.3.c#L219

**Comment by daurnimator** [comment]
@brunoos do you need anything from me for this one?

**Comment by daurnimator** [comment]
Added in https://github.com/brunoos/luasec/commit/96401bdf67ecbd3ad81389099591c7d83107d70b 

awesome!
