### ISSUE TITLE
Support TLS extension servername for the ClientHello in OpenSSL 

### ISSUE THREAD

**Issue by toggledbits** [brunoos/luasec#135]
I've had a devil of a time trying to get LuaSec to connect to a site that uses *gnunicorn*. In playing around, I discovered that if I just `openssl s_client -connect sitename:443`, the connection fails early with an alert 80 error (TLS). 

Further playing, though, reveals that if do `openssl s_client -servername sitename -connect sitename:443`, it connects successfully.

I suspect my LuaSec problems are caused by not setting this option, referred to in the OpenSSL command line help as "TLS extension servername for the ClientHello". Does LuaSec support setting this option for OpenSSL?

**Comment by brunoos** [comment]
Did you try to set SNI on connection?

**Comment by toggledbits** [comment]
I'll have to see if the version I'm using even supports it. Looks like 0.4, and I can't change that (it's on an embedded system). They're doing firmware upgrades, and updating this is a much-requested change.

I'm using the https wrapper as well. The source I have definitely does not set SNI like the later versions. But I also noticed this line: `url.create = tcp(url)`... that still persists in the current version. It would be nice if it checked to see if `url.create` was already set (passed in) and didn't override it unconditionally.

In any case, thanks for the quick reply.
