### ISSUE TITLE
luasec 0.8-1 ssl error on Ubuntu Trusty

### ISSUE THREAD

**Issue by xHasKx** [brunoos/luasec#136]
Hi!

I've found a bug in your last release 0.8-1.
After installing it on Ubuntu Trusty 14.04 amd64 (default build on travis-ci.org) I have an expection when loading "ssl" module using `require("ssl")`:

    ...luamqtt/local/hererocks/v-l5.1/share/lua/5.1/ssl.lua:8: error loading module 'ssl.core' from file 
    '/home/travis/build/xHasKx/luamqtt/local/hererocks/v-l5.1/lib/lua/5.1/ssl.so':
    	/home/travis/build/xHasKx/luamqtt/local/hererocks/v-l5.1/lib/lua/5.1/ssl.so: undefined symbol: SSL_CTX_set1_curves_list

Lua versions: 5.1 and higher

I'ts easily reproducible in virtualbox VM running Ubuntu 14.04 amd64 from live iso, using https://github.com/mpeterv/hererocks for lastest luarocks

Here is an example of failed build on travis-ci.org: https://travis-ci.org/xHasKx/luamqtt/builds/521650087

It's not reproducing when installing previous luasec version 0.7-1

**Comment by brunoos** [comment]
I removed some code from old versions of OpenSSL in order to simplify the code maintenance.

Ubuntu 14.04 uses OpenSSL 1.0.1, that hit end of life support.

I think this is more a missing information that this version needs at least OpenSSL 1.0.2 than a bug. You should use version 0.7 for old versions of OpenSSL.

**Comment by xHasKx** [comment]
Ok, then it would be great to place some "important note" in your documentation about minimal OpenSSL version in the OS with cheat sheet for Ubuntu Trusty 14.04 like this:

    luarocks install luasec 0.7-1

**Comment by daurnimator** [comment]
> Ubuntu Trusty 14.04

Ubuntu 14.04 LTS (Trusty Tahr) Reaches End of Life on April 30, 2019

Considering it has less than 2 weeks left before no one should be using it anymore, I don't see why it deserves a mention.

**Comment by xHasKx** [comment]
I understand that Trusty is almost End of Life, but travis-ci.org is using it by default if exact distributive is not set in config. I'll contact them on this, but changing may take long time for them.

Anyway, people going to documentation when in troubles, and you may save a lot of time for them with only several extra lines in your docs. I thought it was obvious to everyone.

**Comment by brunoos** [comment]
I will add infomation about OpenSSL version, but I think that a sheet for OS is not applicable, since we have serveral Linux distributions and you can install new versions of OpenSSL. List the OS can be interpreted that you need something special from OS.
