### ISSUE TITLE
LuaSec for x64?

### ISSUE THREAD

**Issue by ahmed-shehata** [brunoos/luasec#14]
I have managed to run Luasec under x86 (32-bit) but I could not build it to run under x64, SSL.dll is not found, could you please provide a build?

**Comment by Neustradamus** [comment]
Any news for x64 support?

**Comment by daurnimator** [comment]
luasec has always worked on x64.

**Comment by brunoos** [comment]
Sorry, but I'm not confortable to provide pre-compiled packages for luasec since I barely use Windows to test.
