### ISSUE TITLE
Make it work with coroutine-base schedulers

### ISSUE THREAD

**Issue by capr** [brunoos/luasec#141]
Hi,

I noticed that luasec calls openssl to do the TLS handshake, which makes it incompatible with copas or other coroutine-based schedulers since those schedulers rely on the ability to override accept(), read() and write() in order to make them yield to the scheduler.

Is there a solution to that, other than reimplementing both LuaSec and the TLS protocol in Lua?

Thanks!

**Comment by capr** [comment]
Update: it looks like `dohandshake()` can be called multiple times on a non-blocking socket and it will resume from where it left off the last time. I haven't tried it but it looks like Prosody already uses this feature.

**Comment by mwild1** [comment]
I mentioned this in the Prosody chatroom, but Copas also uses this feature:

- Example: https://keplerproject.github.io/copas/manual.html#ssl
- Code: https://github.com/keplerproject/copas/blob/master/src/copas.lua#L355
