### ISSUE TITLE
LuaSec 0.8 binaries problem

### ISSUE THREAD

**Issue by Sledmine** [brunoos/luasec#142]
Hi i recently compiled the ssl.dll for a project i'm working on but using the compiled dll this error appear on screen:

`
luajit: error loading module 'ssl.core' from file 'C:\Users\Sledmine\Documents\Herramientas\cmder\bin\clib\ssl.dll':
       Cannot find specified module
`
I checked the dll functions using DLLViewer and everything looks ok, any idea why is not working? I really need this dll please any help will be usefull

PD: I have the newest sll.lua, https, etc in my project

**Comment by brunoos** [comment]
I think I didn't change anything about windows in this version.
Can you give more information? How do you build luajit and luasec?

**Comment by Sledmine** [comment]
i build luasec using VS2017 and im using the precompiled luajit from the luapower distribution, i was using the 0.6 luasec from other binary releases but this one is not working, i can't find a binary build of the 0.8 version

**Comment by pkulchenko** [comment]
@Sledmine, I'd use [dependency walker](http://www.dependencywalker.com/) to check on the exact error that happens during DLL load (you can start profiling of the application from the dependency walker and it will show all loaded DLLs and any issues during the process). This should tell you where the dependency chain is failing (maybe there is a mix of 32bit and 64bit libraries or something like that).

**Comment by Sledmine** [comment]
I will check it thanks for the info, btw i was using ssl.dll from the libraries you leave in the Love2D forum @pkulchenko, is the one im using in my project right now but sometimes the 0.6 version throws `"ERROR 'sslv3 alert handshake failure' uknown error..."` this happens randomly im trying to see if 0.8 can help to this

**Comment by Sledmine** [comment]
I asked to my hosting provider and the say everything is ok, i can access via https to it using a web browser  but trying to make a request from my project using ssl throws that error

**Comment by pkulchenko** [comment]
@Sledmine, I'm not sure what version of OpenSSL you are using, but OpenSSL changed the structure of their dependencies, so you may be missing some of them.

I compiled luasec 0.8 against the latest openSSL module (1.1.1c) for [64bit](/download.zerobrane.com/misc/luasec-0.8-openssl-1.1.1c-luasocket-3.0-win64.zip) and [32bit](/download.zerobrane.com/misc/luasec-0.8-openssl-1.1.1c-luasocket-3.0-win32.zip) versions, so you may want to see if those work for you. The new dependencies (libcrypto-1_1.dll and libssl-1_1.dll) are included as well. I tested them using `tlsv1_2` and everything seems to work fine.

**Comment by brunoos** [comment]
@Sledmine, I think you forgot to add the path to libcrypto-1_1.dll and libssl-1_1.dll to your PATH variable.

**Comment by Sledmine** [comment]
> @Sledmine, I'm not sure what version of OpenSSL you are using, but OpenSSL changed the structure of their dependencies, so you may be missing some of them.
> 
> I compiled luasec 0.8 against the latest openSSL module (1.1.1c) for [64bit](/download.zerobrane.com/misc/luasec-0.8-openssl-1.1.1c-luasocket-3.0-win64.zip) and [32bit](/download.zerobrane.com/misc/luasec-0.8-openssl-1.1.1c-luasocket-3.0-win32.zip) versions, so you may want to see if those work for you. The new dependencies (libcrypto-1_1.dll and libssl-1_1.dll) are included as well. I tested them using `tlsv1_2` and everything seems to work fine.

@pkulchenko I can't download your libraries it says "Not Found", i think you removed them, sorry for the late response, if you can provide another link will be helpful, i'm looking to all the possibilities, i will check that @brunoos

**Comment by pkulchenko** [comment]
@Sledmine, I updated the URLs in the [earlier comment](https://github.com/brunoos/luasec/issues/142#issuecomment-500681602); it was missing the protocol for some reason.

**Comment by Sledmine** [comment]
@pkulchenko Thanks, testing right now

**Comment by Sledmine** [comment]
Hmm, it says that the 32bit ssl.dll is not a valid win32 application, i will check using 64bit (i will test using 32bit and 64bit LuaJIT binaries)

**Comment by Sledmine** [comment]
My bad, i accidentaly replaced 32bit LuaJIT binaries using 64bit ones, everything looks like is working, i will be testing for a while, thank you so much @pkulchenko @brunoos everything was really helpful, i'm going to check later why my dll is not working, for now i will be using your binaries @pkulchenko really appreciate it
