### ISSUE TITLE
error Headers

### ISSUE THREAD

**Issue by Existence01** [brunoos/luasec#143]
`local requestHeaders = {["Accept-Encoding"] = "gzip"}`
`local response_body = {}`
`local source = 'a=123'`
`local r, c, h = https.request{
url="xxx.com",method = "POST",
headers=requestHeaders,
source = ltn12.source.string(source),
sink = ltn12.sink.table(response_body)}`
`print(r,c,h) -- 1, 200, table: 0x170481900`
`print(response_body) -- empty string
`
When "Accept-Encoding" is not used, it will run normally.Why?

**Comment by brunoos** [comment]
It's hard to say without something to test.
Did you use other tool to test if the server is working ok?
Did you try to set 'content-length' in requestHeaders?

**Comment by Existence01** [comment]
Thank you. Update to the latest version solved
