### ISSUE TITLE
Static linking LuaSec and LuaSocket conflicts

### ISSUE THREAD

**Issue by capr** [brunoos/luasec#145]
Hi,

LuaSec bundles a partial, modified version of LuaSocket which makes it hard to get a static build containing both LuaSec and LuaSocket because of duplicate symbols in both libraries. Possible solutions include: 

* upstream the changes to LuaSocket so that LuaSec can be built against the official LuaSocket code (the one I like best).
* prefix all non-static LuaSocket functions so to solve the duplicate symbols issues.
* make all LuaSocket functions static and compile everything as a single C translation unit.
* other options?

Thanks.

**Comment by brunoos** [comment]
* Remove 'src/luasocket' directory from luasec, change build files to use luasocket's files, and test it a lot...

All files that luasec uses from luasocket were in a separated directory. The idea was facilitate integration in some way.

LuaSocket is a well known library to socket only, if you merge it with ssl, you will add a heavy dependency (openssl). Providing it with and without ssl will be confusing. The best would be a new project...

**Comment by capr** [comment]
@brunoos The luasocket files found in luasec do not match the v3.0-rc1 luasocket files (which seems to be the latest release according to https://github.com/diegonehab/luasocket/releases) which means either a) luasec uses a modified version of luasocket or b) is using a different luasocket version.  Which one is it?

**Comment by brunoos** [comment]
If you make a `diff`, you will see that there is no semantic changes in functions that luasec uses.

**Comment by capr** [comment]
So there's nothing to fix here from your pov...

**Comment by brunoos** [comment]
nope...

**Comment by capr** [comment]
Great. Keep up the good work!

**Comment by reneboer** [comment]
Hi, there is a difference with rc1 in buffer.c where the timeout is only included in the debug compile. The version you have causes disconnects on sockets that are kept open for a longer time (typically more than a minute). Could you at least change that?
