### ISSUE TITLE
ssl module has no config field

### ISSUE THREAD

**Issue by Zash** [brunoos/luasec#149]
The config table can't be accessed:

```
> print(require"ssl".config)
nil
```

It does not appear to be exported:

https://github.com/brunoos/luasec/blob/2480572bdf8a97c8f0e5839edc63344302eed4c0/src/ssl.lua#L273-L281

**Comment by brunoos** [comment]
yep, this is very wrong...

**Comment by pkulchenko** [comment]
@brunoos, do you plan to release a new version with this change soon?

**Comment by brunoos** [comment]
I hope so... it's about time to a new version with the last changes.
Since this is a bug, it must be backported to 0.7 and 0.8 also.
