### ISSUE TITLE
Compile error when luarocks install luasec

### ISSUE THREAD

**Issue by solio** [brunoos/luasec#153]
`
/usr/bin/ld: /opt/solio/openrestyinstall/openssl/.openssl/lib/libcrypto.a(asn_mime.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /opt/solio/openrestyinstall/openssl/.openssl/lib/libcrypto.a(bio_b64.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /opt/solio/openrestyinstall/openssl/.openssl/lib/libcrypto.a(bio_asn1.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status

Error: Build error: Failed compiling module ssl.so
`
os : centos

**Comment by brunoos** [comment]
OpenSSL libraries were not compiled with relocation support.
You need to rebuild the libraries with -fPIC as the error suggested.
