### ISSUE TITLE
[question] reading and writing on the same socket

### ISSUE THREAD

**Issue by Tieske** [brunoos/luasec#155]
With regular sockets, one could simultaneously read and write on the same socket. When doing a `select`, just provide the same socket in both the reading and writing lists.

How to achieve this with LuaSec? say I have my sockets in both the reading and writing list, and do a `read` and `send`, now during the read process LuaSec returns a `wantwrite`. So now both the reading and writing process/function will have their socket (same one) in the writing list. That won't work, since when it returns it is unclear which function/process should get the data.

What would be the proper way of dealing with this?

**Comment by Tieske** [comment]
My initial thoughts were that the `wantread` and `wantwrite` timeout messages would only be returned during the `dohandshake` phase of the connection, but the docs state that also `read` and `send` can return those messages.

My knowledge in this area is lacking probably, but I would have expected a `send` to just take the data, encrypt and send it. So at most I expected a different size of the final message over the connection, but not a "transactional" style operation, switching between reading/writing.

**Comment by daurnimator** [comment]
> My knowledge in this area is lacking probably, but I would have expected a `send` to just take the data, encrypt and send it. So at most I expected a different size of the final message over the connection, but not a "transactional" style operation, switching between reading/writing.

SSL used to (but not in TLS 1.3) have "renegotiations" where in the middle of a connection you'd need to send/recv new keys for encrypting the traffic.

**Comment by Tieske** [comment]
Ah, that explains it.

Any advice on how to deal with simultaneous reads and writes in this scenario?

**Comment by daurnimator** [comment]
> Any advice on how to deal with simultaneous reads and writes in this scenario?

disable renegotiations (which is recommended behaviour now anyway) and assert that wantread isn't returned for a write and wantwrite isn't returned for a read after the initial handshake.

**Comment by brunoos** [comment]
Justi in case, for long running connection probably you will want a key update.
(I have the impression that TLS 1.3 moved the decitions to application layer)

@Tieske if you are using coroutines, you can suspend/resume easier to repeat the operation that trigger the timeouts. But in other scenarios, it could be a bit more tricky.

**Comment by Tieske** [comment]
I'm trying to figure out how to best update the Copas scheduler. See this `receive` method: https://github.com/keplerproject/copas/blob/57a34f72976dbb35879d31c9471da78b37b842c4/src/copas.lua#L249-L269

Copas supports both reading and writing on the same socket. So the client socket can both be in the reading-set as well as in the writing-set of a call to `select()`.

But if you look at the code I linked above; it does a `client:receive(pattern, part)` and if the returned error is `wantwrite` it yields the client-socket to the writing queue; `coroutine.yield(client, _writing)`.
Now if the same socket is already in that `_writing` queue, it will be overwritten. And the coroutine that was trying to do the `send` will never be resumed.

But if the `select()` that is both reading and writing on the same socket returns it readable, I resume reading. The reading coroutine has no knowledge of the state of the writing socket, whether it was returned writable. 
Now if reading returns a `wantwrite` it means that luasec was unable to get the info it needed. So then we know it was not writeable. So then the writing coroutine needs to be "parked" somewhere, until the reading one stops receiving "wantread"/"wantwrite".
When the reading one either receives data, or gets a regular "timeout" error, the renegotiations should be done, and the "parked" coroutine for writing can be restored.

(just rubber ducking here 🦆 )

**Comment by brunoos** [comment]
OpenSSL will not return "timeout", it always return "wantread"/"wantwrite". See [SSL_get_error](https://www.openssl.org/docs/man1.1.1/man3/SSL_get_error.html).

Maybe, you could be more safer and test "wantread" in `if == "wantwrite"  else  ...  end`

Note that `send()` returns "wantwrite" and `receive()` returns "wantread" is normal. I would take action if I received a inverted "want".

For example, if you call `send()` and it returns "wantread", you can postponed the same socket in the read queue, than retry the `send()` until "wantwrite" or sucess.

Of course, it easier to say...

A question: `_doTick()` is the scheduler? It seems that it does not make the decision of the queues. Would it be better if `send()` and `receive()` return what happened, and the scheduler decides about the queue?

**Comment by Tieske** [comment]
the queue is decided upon with the `yield`, see here for example: https://github.com/keplerproject/copas/blob/2eb202f6b5b6a8c1ad87e06a8f2d5cd58e89e7de/src/copas.lua#L274

The results of this `yield` are then passed back to `_doTick` which adds the client socket again to the queue that it received back. See https://github.com/keplerproject/copas/blob/2eb202f6b5b6a8c1ad87e06a8f2d5cd58e89e7de/src/copas.lua#L588

So I think the current code is ok, for the switching between reading/writing based on the "wantread" and "wantwrite" messages.

It is just that whenever a "want" error is returned, I must park the same socket that might already be in the other queue already (due to simultaneous reading/writing on the same socket), to prevent overwriting that queue entry. And once the "want" errors are gone, the parked socket should be returned to its original queue.

**Comment by Tieske** [comment]
re-reading the message;

> Would it be better if send() and receive() return what happened, and the scheduler decides about the queue?

Maybe, from a socket perspective, the individual functions could all return "wantread", "wantwrite" (even for regular ones; read method, "wantread" or send method, "wantwrite". And then the `_doTick` could insert them in the appropriate queue.

What that wouldn't cover is other threads being scheduled, timers, and other tasks.

Need to give that some thought.

**Comment by brunoos** [comment]
Look, that was just a question, you do not need to change if it is ok... ;)
When you called it "scheduler" I thought it controlled the queues...

**Comment by Tieske** [comment]
I think my question has been answered. Thx!
