### ISSUE TITLE
Error when trying to install with luarocks

### ISSUE THREAD

**Issue by jokru** [brunoos/luasec#157]
I have OpenSSL working, I have tried to set OPENSSL_DIR to every logical path it could be, but still same error.

Error: Could not find expected file openssl/ssl.h for OPENSSL -- you may have to install OPENSSL in your system and/or set the OPENSSL_DIR variable

**Comment by brunoos** [comment]
Could tou tive more information about your system and path you use.

**Comment by jokru** [comment]
I'm running windows 10 and have installed OpenSSL on my D-drive

**Comment by jokru** [comment]
Alright, when I give the path to openSSL during the install I get an error about a command "cl" missing.

**Comment by jokru** [comment]
The command I'm using is
`luarocks install luasec OPENSSL_DIR=D:\Programs\OpenSSL-Win64`

**Comment by jokru** [comment]
Okay, I dont know if this can be called progress, but now I instead get the error:
`Installing http://luarocks.org/repositories/rocks/luasec-0.9-1.src.rock...
cl /MD /O2 -c -Fosrc/options.obj -IC:/Program Files (x86)/Lua/5.1/include src/options.c -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -DLSEC_EXPORTS -DBUFFER_DEBUG -DLSEC_API=__declspec(dllexport) -DWITH_LUASOCKET -DLUASOCKET_DEBUG -DLUASEC_INET_NTOP -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DNTDDI_VERSION=0x05010300 -ID:\Programs\OpenSSL-Win64/include -Isrc/ -Isrc/luasocket
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28319 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

options.c
c1: fatal error C1083: Cannot open source file: 'src/options.c': No such file or directory

Error: Build error: Failed compiling object src/options.obj`

**Comment by jokru** [comment]
And when trying to build with visual studio code I receive an error: 
`LNK1104 cannot open file 'libeay32MDd.lib'`

**Comment by brunoos** [comment]
Do you have this library on your system?
Did you set `OPENSSL_LIB_DIR`?

In the last case, you can download the rockspec file, edit for your libraries and install using:
`luarocks install luasec-XXX.rockspec`

**Comment by Tieske** [comment]
Windows is hard. You have OpenSSL installed, but did you build it locally? do you have the related headers available?

You might be better of asking support in the Lua mailing list or in LuaRocks.

**Comment by Tieske** [comment]
here's what I did a loooong time ago; http://www.thijsschreijer.nl/blog/?p=899

**Comment by jokru** [comment]
The way I've bypassed this for now is by using a docker container
