### ISSUE TITLE
Fails in Lua 5.1 and 5.2 but OK in 5.3

### ISSUE THREAD

**Issue by LiamFry** [brunoos/luasec#162]
I'm installing LuaSec 0.9 via LuaRocks 3.3.1 with OpenSSL 1.1.1g (via MacPorts).

I use `luarocks install OPENSSL_DIR=/opt/local luasec`

The compilation/installation is successful for Lua 5.1, 5.2, and 5.3

However, when I attempt to use it, I get errors, as follows:

 1. Lua 5.1
- `dlopen(/usr/local/lib/lua/5.1/ssl.so, 2): Symbol not found: _luaL_checkversion_`
 2. Lua 5.2
- `dlopen(/usr/local/lib/lua/5.2/ssl.so, 6): Symbol not found: _lua_rotate`
 3. Lua 5.3
- success

**Comment by daurnimator** [comment]
This looks like you compiled against 5.3 and placed where 5.1/5.2 are looking.
How did you tell your luarocks to compile for 5.1/5.2?

**Comment by LiamFry** [comment]
My understanding is that the current version of LuaRocks will determine where to place a rock based on the active Lua version, e.g. if Lua 5.2 is active, installs are placed in `/usr/local/{share,lib}/lua/5.2`, etc.
I *never* had an issue with LuaRocks 2.4.4 and `--versioned-rocks-dir` -- but apparently that option is no longer available. 
I'm so very confused. Since upgrading to LuaRocks 3.3.1, all my rocks are broken.

I installed LuaRocks three times:
`# activate Lua 5.1`
`./configure --lua-version=5.1 --with-lua=/usr/local && make build && sudo make install`
`# activate Lua 5.2`
`./configure --lua-version=5.2 --with-lua=/usr/local && make build && sudo make install`
`# activate Lua 5.3`
`./configure --lua-version=5.3 --with-lua=/usr/local && make build && sudo make install`

I assumed this was successful bc. I now have `/usr/local/share/lua/5.[123]/luarocks/`

I agree; the results I posted in my original message strongly suggests that `luasec` was built for 5.3 (each time) and placed in 5.1, 5.2, and 5.3  Without `--versioned-rocks-dir` and three versions of LuaRocks, how am I supposed to install the same rock for each version of Lua?

**Comment by LiamFry** [comment]
Turns out this is not a `luasec` or Lua issue; it's an issue with LuaRocks after upgrading to the latest version. The situation has been resolved; see [here](https://github.com/luarocks/luarocks/issues/1209).
