### ISSUE TITLE
ssl.https.request - how to detect an invalid cert?

### ISSUE THREAD

**Issue by sandervanburken** [brunoos/luasec#165]
[ssl.https.request](https://github.com/brunoos/luasec/blob/master/src/https.lua#L115) does not seem to detect invalid certs. Is there something I need to configure to make it do that?

    > ssl_https = require('ssl.https')
    > require 'pl'
    > http_response, status_code, headers, status = ssl_https.request('https://self-signed.badssl.com/')
    > pretty.dump(http_response)
    [[<!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="shortcut icon" href="/icons/favicon-red.ico"/>
      <link rel="apple-touch-icon" href="/icons/icon-red.png"/>
      <title>self-signed.badssl.com</title>
      <link rel="stylesheet" href="/style.css">
      <style>body { background: red; }</style>
    </head>
    <body>
    <div id="content">
      <h1 style="font-size: 12vw;">
        self-signed.<br>badssl.com
      </h1>
    </div>
    
    </body>
    </html>
    ]]
    > print(status_code)
    200
    > pretty.dump(headers)
    {
      connection = "close",
      date = "Thu, 04 Feb 2021 16:01:34 GMT",
      ["last-modified"] = "Tue, 24 Mar 2020 00:15:54 GMT",
      ["cache-control"] = "no-store",
      ["accept-ranges"] = "bytes",
      ["content-type"] = "text/html",
      etag = "\"5e79513a-1f6\"",
      ["content-length"] = "502",
      server = "nginx/1.10.3 (Ubuntu)"
    }
    > print(status)
    HTTP/1.1 200 OK

**Comment by brunoos** [comment]
Did you try to set `verify` parameter?

https://github.com/brunoos/luasec/wiki/LuaSec-1.0#https_request

**Comment by sandervanburken** [comment]
Thank you! I did not understand how to set it. It works!

```
> ssl_https = require('ssl.https')
> http_response, status_code, headers, status = ssl_https.request {
>> url = 'https://self-signed.badssl.com/',
>> verify = 'peer'}
> print(status)
nil
> print(http_response)
nil
> print(status_code)
certificate verify failed
```

**Comment by daneov** [comment]
@brunoos Do you know if the code above is correct? Because I'm unsure how to accomplish this (accepting a valid, rejecting invalid cert) as well 😬 Thanks for the help!

**Comment by pkulchenko** [comment]
@sandervanburken, @daneov, you may need to specify `cafile = "/path/to/downloaded/cacert.pem"` parameter, otherwise your client doesn't know where to get the certificates to use in validation. I have an old example posted here (http://notebook.kulchenko.com/programming/https-ssl-calls-with-lua-and-luasec), which should still be valid.

**Comment by sandervanburken** [comment]
@pkulchenko thank you for your response. I tried it but still no success.

```sh
/tmp # wget http://curl.haxx.se/ca/cacert.pem
Connecting to curl.haxx.se (151.101.2.49:80)
Connecting to curl.haxx.se (151.101.2.49:443)
Connecting to curl.se (151.101.194.49:443)
cacert.pem           100% |**********************************************************************************************************************************************************************************************|   203k  0:00:00 ETA
/tmp # head cacert.pem
##
## Bundle of CA Root Certificates
##
## Certificate data from Mozilla as of: Tue Jan 19 04:12:04 2021 GMT
##
## This is a bundle of X.509 certificates of public Certificate Authorities
## (CA). These were automatically extracted from Mozilla's root certificates
## file (certdata.txt).  This file can be found in the mozilla source tree:
## https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt
##
/tmp # cat <<EOH | lua
> https = require('ssl.https')
> one, code, headers, status = https.request {
>   url = "https://www.site.com.br",
>   protocol = "any",
>   options = "all",
>   verify = "peer",
>   cafile = "/tmp/cacert.pem",
> }
> print(one)
> print(code)
> print(headers)
> print(status)
>
> one, code, headers, status = https.request {
>   url = "https://www.site.com.br",
>   protocol = "any",
>   options = "all",
>   verify = "client_once",
>   cafile = "/tmp/cacert.pem",
> }
> print(one)
> print(code)
> print(headers)
> print(status)
> EOH
nil
certificate verify failed
nil
nil
nil
certificate verify failed
nil
nil
```

**Comment by brunoos** [comment]
Which version of luasec are you using?

I did the same thing you showed:
<pre>
1
200
table: 0x55a322ced440
HTTP/1.1 200 OK
1
200
table: 0x55a322db91e0
HTTP/1.1 200 OK
</pre>

**Comment by sandervanburken** [comment]
I just tried it again on Alpine and Ubuntu docker containers. Both work fine!

I did not write down what exact version I used last time. So I cannot be sure if I replicated the same test as before.

Most likely I made a mistake with my test and unintentionally gave you a red herring.

Sorry for my delayed response and thank you for your support!
