### ISSUE TITLE
Https timeout not working

### ISSUE THREAD

**Issue by 7i77an** [brunoos/luasec#168]
I'm trying to set an execution timeout in https.
With http it works correctly but with https it does not work.

This is my example code:

local url = self:makeUrl(path, urlParams)
body = body or ""
headers = headers or {}
headers["Content-Length"] = tostring(#body)
if contentType then
	headers["Content-Type"] = contentType
end

local http = require "socket.http"
http.TIMEOUT = self.timeoutSeconds

local caller
if self.ssl then
	local Synchronize = require "Synchronize"
	caller = Synchronize("luasec_mutex", function()
		return require ("ssl.https")
	end)
else
	caller = http
end

local source = ltn12.source.string(body)
local response_body = {}
local ok, response_code, response_headers, response_status_line = caller.request({
	url = url,
	method = method,
	headers = headers,
	source = source,
	sink = ltn12.sink.table(response_body)
})

**Comment by brunoos** [comment]
Did you set "https.TIMEOUT" ?

**Comment by 7i77an** [comment]
Thank you very much for your answer, it works fine.
