### ISSUE TITLE
SFTP Protocol

### ISSUE THREAD

**Issue by 7i77an** [brunoos/luasec#169]
Is it possible to build a layer similar to what has been done for https and be able to use sftp from the ftp.lua that is in the luasocket?

The only library I found for lua is lua-cURL and I think it is not the best option.

**Comment by brunoos** [comment]
I don't know how SFTP protocol works. In any case, I think that this should be a new project more integrated than http and https are today.

**Comment by 7i77an** [comment]
Ok, thanks.
