### ISSUE TITLE
ssl.https.request dont work

### ISSUE THREAD

**Issue by YarickDarknet** [brunoos/luasec#171]
`lua: /usr/share/lua/5.4/ssl/https.lua:66: bad argument #2 to 'method' (string expected, got light userdata)
stack traceback:
        [C]: in function 'socket.http.request'
        /usr/share/lua/5.4/ssl/https.lua:132: in function 'ssl.https.request'
`

**Comment by brunoos** [comment]
Can you give a small code example of the problem?

You can see the documentation of `https.request` at:
http://w3.impa.br/~diego/software/luasocket/http.html#request

**Comment by carlocab** [comment]
Seeing this error at Homebrew CI too. In particular, it's this problem: https://github.com/luarocks/luarocks/issues/1302

Will try to extract an example, but currently my way of reproducing it is to install `luasec` then try to install any other rock.

**Comment by YarickDarknet** [comment]
@brunoos 
[itdontwork.lua.txt](https://github.com/brunoos/luasec/files/6365919/itdontwork.lua.txt)

**Comment by brunoos** [comment]
The problem seems to be with luasocket... luasec's `https` is a wrapper to luasocket's `http` module.
Could it be luaL_Buffer problem in Lua 5.4.3?

**Comment by brunoos** [comment]
It seems Lua 5.4.3 broke luasocket... it work fine with Lua 5.4.2.

**Comment by brunoos** [comment]
The function `buffer_meth_receive` expects 3 parameters, with parameters 2 and 3 being optional.

However, `luaL_buffinit` can push values into the stack and that is breaking the function if 2 or 3 are missing.

One solution is always push nothing for 2 and 3 if they are missing. Something ugly like this seems to work:

<pre>
int buffer_meth_receive(lua_State *L, p_buffer buf) {
+    if (lua_gettop(L) < 3) lua_settop(L, 3);
    int err = IO_DONE, top = lua_gettop(L);
</pre>

Of course, all the code needs to be reviewed now.
