### ISSUE TITLE
Off by one in `cert:validat(notafter)`

### ISSUE THREAD

**Issue by Zash** [brunoos/luasec#173]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1715455 I was made aware that certificates are valid the exact second given in the `notAfter` timestamp. LuaSec apparently gets this wrong too, as demonstrated by the following test case:

<details><summary>local cert = require"ssl".loadcertificate(...)</summary>
<pre>
local cert = require"ssl".loadcertificate[[
-----BEGIN CERTIFICATE-----
MIIDCTCCAfGgAwIBAgIUDkExxWgauf6NaaJj8OsCr77NYegwDQYJKoZIhvcNAQEL
BQAwFDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTIxMDYxNDEyNDc1MVoXDTIyMDYx
NDEyNDc1MVowFDESMBAGA1UEAwwJbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAs7OJ/YtndbvFJLK+JYf+JwADkexXUXiofPyZHYVN6ds1
oGAUsnshsQuihY4utcqzzK9a5WucKDps3uS5TpnFzAuDyPyc0POUHj6OVWuZgHQR
nHmITMVKsXs//SIGmmlhoCGnNlvoB4jgfkojBoiZFoaN1NZltcNM8YRMewcysQwy
y8XoyYGI2x8QVFN7qxu2llTD31/w0zZLVbjIA+cSH1TZfGxJr5s5nh2PqApsdzFU
u5ySEHqxT63i5xgTKdcgK8ij55nT3ozHgzj/MRmLAZsSKWD6Qicdvp59v0VhhB78
raIan4yuKoaGOjWaOr7OMdb8GUIINFUNBLvhlKfNFQIDAQABo1MwUTAdBgNVHQ4E
FgQUfFSJak2AVQZ/RjAog+ZJcdWJMOIwHwYDVR0jBBgwFoAUfFSJak2AVQZ/RjAo
g+ZJcdWJMOIwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAFOhM
f6n8cXzOfeUopWczNdHEtbRCUGwn0jHS6vixR3b2BPKm/AMz2tSQpoA+KpFo5QHb
6Nve1cHdtmKC9zwmr8elB64djZTuvo4tl8XW+1L4OHj2u5u5ro9m7AX0jJyMf6Ft
5Vxh0soeb9s+XEhQGV+dg4elaEtZHoHCKwqkbJcd02PfpWVFtwJpF9IW2Qbk703J
cV+d22RFgrx7ih2zplKw3tsL6JOEtrjHDsTjF7Lm5OX3Fpdv31KMn4/za02tVYDj
GsUpUPFQ1ClsSwePVcVYbQ6mjxv4Oltw5oj9osbtH6mpV4PqNx69LDWoIynJGYxC
7Vfbtra+9lnmFo8n2A==
-----END CERTIFICATE-----
]]
</pre>
</details>

```lua
local notafter = 1655210871;
local notafter_formatted = "Jun 14 12:47:51 2022 GMT";

assert(cert:notafter() == notafter_formatted);
assert(os.date("!%b %e %H:%M:%S %Y GMT", notafter) == notafter_formatted)

assert(cert:validat(notafter-1), "valid before expiry")
assert(not cert:validat(notafter+1), "not valid after expiry")
assert(cert:validat(notafter), "valid at expiry") -- fails
```

**Comment by brunoos** [comment]
Does this patch fix the problem?
```
--- a/src/x509.c
+++ b/src/x509.c
@@ -485,10 +485,13 @@ static int meth_digest(lua_State* L)
  */
 static int meth_valid_at(lua_State* L)
 {
+  int nb, na;
   X509* cert = lsec_checkx509(L, 1);
   time_t time = luaL_checkinteger(L, 2);
-  lua_pushboolean(L, (X509_cmp_time(X509_get0_notAfter(cert), &time)     >= 0
-                      && X509_cmp_time(X509_get0_notBefore(cert), &time) <= 0));
+  nb = X509_cmp_time(X509_get0_notBefore(cert), &time);
+  time -= 1;
+  na = X509_cmp_time(X509_get0_notAfter(cert),  &time);
+  lua_pushboolean(L, nb == -1 && na == 1);
   return 1;
 }
```

PS: `X509_cmp_time` returns `0` on error, so the previews version already has some kind of problem.

**Comment by Zash** [comment]
> Does this patch fix the problem?

Looks good and it seems to work. :+1:

> PS: X509_cmp_time returns 0 on error, so the previews version already has some kind of problem.

Indeed.
