### ISSUE TITLE
[HTTPS] Problems with memory consumption when loading the CA certificate

### ISSUE THREAD

**Issue by mprevide** [brunoos/luasec#174]
I'm having memory consumption issues when loading the CA certificate.

I am using code similar to:

```
local https = require "ssl.https"

https.TIMEOUT = 1

local params="response_mode=decision"

local header_request = {}
header_request["Content-Type"] = "application/x-www-form-urlencoded"
header_request["Accept"] = 'application/json'
header_request["content-length"] = string.len(params)

local base_request = {}
base_request.method = "POST";
base_request.url = "https://domain.com";
base_request.source = ltn12.source.string(params);
base_request.headers = header_request;
base_request.sink = ltn12.sink.table(response);
base_request['protocol']="any"
base_request['options']= { "all",
    "no_sslv2",
    "no_sslv3",
    "no_tlsv1",
    "no_tlsv1_1"
}

local res, code = https.request (base_request)
local message = table.concat (response)

collectgarbage("collect")
``` 

When I run the above code and call at the end ``collectgarbage("collect")`` the memory consumption stays stable. However when I add a ca certificate adding ``base_request['cafile']="/etc/ssl/certs/ca-certificates.crt"`` and I change verify to peer, adding ``base_request['verify']="peer"`` in the code above before calling ``https.request``, the memory starts to increase consumption fast, reaching very high values and never goes back to how it was before, the memory usage doesn't even decrease, even though the code doesn't run for a long time and I keep calling ``collectgarbage("collect")`` every time at the end.

The functionality of the code works as I expect. Every time the plugin receives a request that must go through my plugin, this request that I described is made and it works as expected, except of course for the memory consumption.

Do you have any idea what it might be?  Memory Leak?
In this case I use the lua script in a kong plugin.

I testing using the latest version 1.0.1-1 and 0.9-1.

**Comment by Tieske** [comment]
@mprevide just a heads up; for a Kong Plugin you should not be using LuaSec, since it uses Lua-Socket under the hood, which uses blocking IO and hence will block the entire workerprocess in a Kong instance. You should be using OpenResty specific socket functions.

btw; this doesn't mean that LuaSec doesn't have problem, that might still exist.

**Comment by brunoos** [comment]
I setup a HTTPS server, put your code in a loop (with the changes) and the memory stay stable.

Do you tested it without kong?

**Comment by mprevide** [comment]
> Lua-Socket

Thank you so much for the tip! I didn't know, I saw several plugins using it and I thought it wasn't a Lua-Socket problem. I don't know much about lua, it was my first script.

**Comment by mprevide** [comment]
I changed it to use "resty.http" and things now work ok.
