### ISSUE TITLE
method `conn:shutdown()` is missing

### ISSUE THREAD

**Issue by Tieske** [brunoos/luasec#181]
while writing compatibility stuff I ran into this method missing in LuaSec. Whilst LuaSocket does have it.

would it be possible to add the method? Or provide any hints as where/how to add it?

**Comment by brunoos** [comment]
I do not remember why it is not implemented, but I think because the LuaSocket´s shutdown() has a mode as parameter that cannot be mapped directly to OpenSSL.

https://aiq0.github.io/luasocket/tcp.html#shutdown
https://www.openssl.org/docs/man1.1.1/man3/SSL_shutdown.html

**Comment by Tieske** [comment]
ah, that explains it. But then wouldn't it make sense (to be compatible) to implement it but ignore the parameter if it is provided, meaning that LuaSec would always use the "both" option as specified by LuaSocket. And then document the discrepancy in behavior between the two?

**Comment by Tieske** [comment]
Reading the links, I assume that a plain TCP socket can shutdown either receive or send. But with TLS, even for just reading, there might be reads and writes required on the TCP level, hence my guess is that with TLS you can either shutdown both, or none. No expert on this topic however...

**Comment by brunoos** [comment]
It seems that`SSL_shutdown()` just closes the TLS part, the socket is still usable.  So, implement `conn:shutdown()`as "closing everything" is possible, but it changes the semantic from `SSL_shutdown()` and this can cause some confusion. I think that use `conn:close()` for now is better.
