### ISSUE TITLE
Is openssl 1.0.2 supported with lua 5.1 release?

### ISSUE THREAD

**Issue by dhruv459** [brunoos/luasec#182]
I installed luaSec using the following command. The openssl libraries (libssl and libcrypto) were present under /usr/local/lib. 

`luarocks install luasec OPENSSL_LIBDIR=/usr/local/lib/`

I am using openresty (Lua + nginx) as an application gateway and while starting it, I am seeing the following error: 

$ error loading module 'ssl.core' from file '/usr/local/lib/lua/5.1/ssl.so':
$ nginx[5426]: #011/usr/local/lib/lua/5.1/ssl.so: undefined symbol: OPENSSL_sk_num

The symbol in question here: `OPENSSL_sk_num` is present in openssl-1.1.1k version but I searched through openssl libraries under 1.0.2 and I am not able to find the symbol there. Wanted to check if whatever I am doing here is supported or not?

**Comment by brunoos** [comment]
Is it possible that luarocks is using headers from OpenSSL from 1.1.1 to compile and linking with libraries from 1.0.3?

Did you try to set OPENSSL_INCDIR=/path/to/openssl/1.0.3/headers in the command line?

**Comment by dhruv459** [comment]
Yes, that worked for me. Referencing the OPENSSL_INCDIR worked fine.
