### ISSUE TITLE
Sumneko's Lua language server shows a warning for passing 2 variables to a function with only 1 argument in https.lua

### ISSUE THREAD

**Issue by C3pa** [brunoos/luasec#186]
[This ](https://github.com/brunoos/luasec/blob/d7161ca0267c0d7a8581a4493f26927c119116de/src/https.lua#L96)is the offending line:

![161394773-6096758f-18cf-4b4a-8792-6d4d46ceda61](https://user-images.githubusercontent.com/41503714/161399588-0d4ce0c4-2477-4eb2-9328-aac3d5d912dd.png)

Some context: Sumneko's Lua language server is the most widely used extension in VS Code for Lua support. It would be nice if we didn't get that warning.

Isn't the second parameter, `getmetatable(self.sock)`, just discarded and can be removed?

**Comment by brunoos** [comment]
Yes, it is discarded.
`reg()` will get metatable again.
