### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Neustradamus** [brunoos/luasec#189]
Hi @brunoos,

Can you see to create a new release with this https://github.com/brunoos/luasec/pull/187?

It is really important for security...

Can you look at the same time other PRs?

Example:
- https://github.com/brunoos/luasec/pull/188
- https://github.com/brunoos/luasec/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

Thanks in advance.

**Comment by brunoos** [comment]
done

**Comment by Neustradamus** [comment]
@brunoos: Thanks a lot!

**Comment by Neustradamus** [comment]
@brunoos: Little detail on https://luarocks.org/modules/brunoos/luasec, I see "scm-1", I think you can remove it?

**Comment by Neustradamus** [comment]
@brunoos: Little detail on https://luarocks.org/modules/brunoos/luasec, I see "scm-1", I think you can remove it?
