### ISSUE TITLE
Failed to install with mingw64

### ISSUE THREAD

**Issue by milen-prg** [brunoos/luasec#190]
I use msys2 mingw64 on Windows 10 Pro 64bit to install luasec from luarocks and it returns old error:

$ luarocks install --global luasec
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llibssl32MD: No such file or directory
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llibcrypto32MD: No such file or directory
collect2.exe: error: ld returned 1 exit status
Installing https://luarocks.org/luasec-1.2.0-1.src.rock

luasec 1.2.0-1 depends on lua >= 5.1 (5.4-1 provided by VM)
luasec 1.2.0-1 depends on luasocket (3.1.0-1 installed)
gcc -O2 -fPIC -c -o src/options.o -IC:/msys64/mingw64/include src/options.c -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -DLSEC_EXPORTS -DBUFFER_DEBUG -DLSEC_API=__declspec(dllexport) -DWITH_LUASOCKET -DLUASOCKET_DEBUG -DLUASEC_INET_NTOP -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DNTDDI_VERSION=0x05010300 -IC:\msys64\mingw64/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -c -o src/config.o -IC:/msys64/mingw64/include src/config.c -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -DLSEC_EXPORTS -DBUFFER_DEBUG -DLSEC_API=__declspec(dllexport) -DWITH_LUASOCKET -DLUASOCKET_DEBUG -DLUASEC_INET_NTOP -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DNTDDI_VERSION=0x05010300 -IC:\msys64\mingw64/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -c -o src/ec.o -IC:/msys64/mingw64/include src/ec.c -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -DLSEC_EXPORTS -DBUFFER_DEBUG -DLSEC_API=__declspec(dllexport) -DWITH_LUASOCKET -DLUASOCKET_DEBUG -DLUASEC_INET_NTOP -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DNTDDI_VERSION=0x05010300 -IC:\msys64\mingw64/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -c -o src/x509.o -IC:/msys64/mingw64/include src/x509.c -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -DLSEC_EXPORTS -DBUFFER_DEBUG -DLSEC_API=__declspec(dllexport) -DWITH_LUASOCKET -DLUASOCKET_DEBUG -DLUASEC_INET_NTOP -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DNTDDI_VERSION=0x05010300 -IC:\msys64\mingw64/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -c -o src/context.o -IC:/msys64/mingw64/include src/context.c -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -DLSEC_EXPORTS -DBUFFER_DEBUG -DLSEC_API=__declspec(dllexport) -DWITH_LUASOCKET -DLUASOCKET_DEBUG -DLUASEC_INET_NTOP -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DNTDDI_VERSION=0x05010300 -IC:\msys64\mingw64/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -c -o src/ssl.o -IC:/msys64/mingw64/include src/ssl.c -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -DLSEC_EXPORTS -DBUFFER_DEBUG -DLSEC_API=__declspec(dllexport) -DWITH_LUASOCKET -DLUASOCKET_DEBUG -DLUASEC_INET_NTOP -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DNTDDI_VERSION=0x05010300 -IC:\msys64\mingw64/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -c -o src/luasocket/buffer.o -IC:/msys64/mingw64/include src/luasocket/buffer.c -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -DLSEC_EXPORTS -DBUFFER_DEBUG -DLSEC_API=__declspec(dllexport) -DWITH_LUASOCKET -DLUASOCKET_DEBUG -DLUASEC_INET_NTOP -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DNTDDI_VERSION=0x05010300 -IC:\msys64\mingw64/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -c -o src/luasocket/io.o -IC:/msys64/mingw64/include src/luasocket/io.c -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -DLSEC_EXPORTS -DBUFFER_DEBUG -DLSEC_API=__declspec(dllexport) -DWITH_LUASOCKET -DLUASOCKET_DEBUG -DLUASEC_INET_NTOP -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DNTDDI_VERSION=0x05010300 -IC:\msys64\mingw64/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -c -o src/luasocket/timeout.o -IC:/msys64/mingw64/include src/luasocket/timeout.c -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -DLSEC_EXPORTS -DBUFFER_DEBUG -DLSEC_API=__declspec(dllexport) -DWITH_LUASOCKET -DLUASOCKET_DEBUG -DLUASEC_INET_NTOP -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DNTDDI_VERSION=0x05010300 -IC:\msys64\mingw64/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -c -o src/luasocket/wsocket.o -IC:/msys64/mingw64/include src/luasocket/wsocket.c -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -DLSEC_EXPORTS -DBUFFER_DEBUG -DLSEC_API=__declspec(dllexport) -DWITH_LUASOCKET -DLUASOCKET_DEBUG -DLUASEC_INET_NTOP -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DNTDDI_VERSION=0x05010300 -IC:\msys64\mingw64/include -Isrc/ -Isrc/luasocket
gcc  -shared -o ssl.dll src/options.o src/config.o src/ec.o src/x509.o src/context.o src/ssl.o src/luasocket/buffer.o src/luasocket/io.o src/luasocket/timeout.o src/luasocket/wsocket.o -LC:\msys64\mingw64 -LC:\msys64\mingw64/bin -llibssl32MD -llibcrypto32MD -lws2_32 C:/msys64/mingw64/bin/lua54.dll -lm
Warning: falling back to wget - install luasec to get native HTTPS support

Error: Build error: Failed compiling module ssl.dll

**Comment by brunoos** [comment]
Do you have libssl32MD and llibcrypto32MD libraries installed? It seems you are using 64bits migwin, the libraries could be different.

**Comment by milen-prg** [comment]
There are no libssl32MD and llibcrypto32MD packages in msys2 mingw64 repositories 😕

**Comment by brunoos** [comment]
But, do you have libsslXX and libcryptoXX ?

**Comment by milen-prg** [comment]
In msys2 mingw64 (64bit) /on Windows 10 Pro 64bit/ has only these packages:
mingw-w64-x86_64-openssl   and   mingw-w64-x86_64-libgcrypt

Unfortunately this is not linux equivalent system, so has many restrictions, may be it is impossible to build luasec. Will write to msys2 team about the using of their package: mingw-w64-x86_64-lua-luarocks

**Comment by brunoos** [comment]
Sorry, I should have explained it better. libsslXX and libcryptoXX are libraries, not packages. You need to find the packages that install them.

Like I said, the name of the libraries can be different. You can download the original rockspec from:
`https://github.com/brunoos/luasec/blob/master/luasec-1.2.0-1.rockspec`

and change the libraries' name inside the file in "windows" section. Then, install luasec with:
`luarocks install luasec-1.2.0-1.rockspec`

**Comment by milen-prg** [comment]
Thank you, very, very much!
I'm not good in so low level programming and this problem I alone will never solve.

The libraries names in msys2 system are simply: libssl and libcrypto without other symbols at the end. I download the luasec-1.2.0-1.rockspec, edit it (row 90) and SUCCESSFULLY install the luasec!!! Great!
Thank you, again!
