### ISSUE TITLE
Server with multiple certificates

### ISSUE THREAD

**Issue by xnyhps** [brunoos/luasec#27]
OpenSSL makes it possible to add multiple different certificates for the sever to use. For example, a (EC)DSA and a RSA cert, where the selected cipher determines which certificate to use. With the SHA1 deprecation coming up, the recommended setup to maintain compatibility is a RSA cert signed using SHA1 and a ECDSA cert signed using SHA256.

LuaSec's API does not make it easy to add multiple certificates. Calling `loadcert` and `loadkey` manually after creating a new context is possible, but annoying.

I propose to make it possible to specify `cert` and `key` as lists when calling `newcontext`. They must be of equal length and added one by one.

**Comment by github-k8n** [comment]
Is there any progress/change regarding this? luasec (used by prosody) is one of the remaining holdouts regarding the possibility to use dual ecdsa/rsa certificates.

**Comment by dan-corneanu** [comment]
Is there any progress on this one?
