### ISSUE TITLE
LibreSSL compatibility

### ISSUE THREAD

**Issue by VanNostrand** [brunoos/luasec#29]
Hi, this compile error happens when compiling against libressl:
```
ssl.c: In function 'meth_compression':
ssl.c:404:3: error: unknown type name 'COMP_METHOD'
   const COMP_METHOD *comp;
   ^
<builtin>: recipe for target 'ssl.o' failed
```

**Comment by daurnimator** [comment]
COMP_METHOD still exists in libressl: https://github.com/libressl-portable/openbsd/blob/master/src/lib/libssl/src/crypto/comp/comp.h

Maybe some extra header needs to be included?

**Comment by VanNostrand** [comment]
libressl has this typedef in include/openssl/comp.h; the sources compile with libressl if #include <openssl/comp.h> is added to ssl.c

**Comment by sortie** [comment]
Compression support was removed from LibreSSL. The inclusion of <openssl/comp.h> from <openssl/ssl.h> was removed the http://freshbsd.org/commit/openbsd/b13dbd20ab3f5c4544ee24eeb184ab912dd9808a?diff=lib%2Flibssl%2Fsrc%2Fssl%2Fssl.h change. On LibreSSL, meth_compression should just unconditonally return no compression is being used. (Or the interface could be removed?) LibreSSL unconditonally defines OPENSSL_NO_COMP to signal it has no compression support. You could use that macro to control whether the compression interfaces are used.

**Comment by brunoos** [comment]
Merged, thanks!
