### ISSUE TITLE
http redirects are silently allowed

### ISSUE THREAD

**Issue by Tieske** [brunoos/luasec#35]
See these lines; https://github.com/brunoos/luasec/blob/1ab6fac9197b194ea94166dff7ad81579f6113ed/src/https.lua#L122-L123

LuaSocket http module blocks redirects only if `url.redirect` is explicitly set to `false`. Hence the test here, allows `nil` to pass and makes LuaSocket execute the redirect.

**Comment by brunoos** [comment]
Since LuaSec does not support redirects, would it be better to keep as it is now?

And, when we solve the redirect problem in LuaSec, do we adopt the same semantics as LuaSocket?

**Comment by Tieske** [comment]
Let's close this in favour of the discussion in #34
