### ISSUE TITLE
wantread/wantwrite

### ISSUE THREAD

**Issue by Tieske** [brunoos/luasec#40]
The wiki says (under `dohandshake`);
> "wantread" indicates that the operation was not finished because a timeout in the underline TCP connection prevents it of sending data.

This is rather cryptic, but it says that "I'm sending data, and I want my counterpart to READ; wantread"

The example given does it exactly the other way around;
```lua
local succ, msg
conn:settimeout(0)
while not succ do
  succ, msg = conn:dohandshake()
  if msg == "wantread" then
    socket.select({conn}, nil)        --> select for reading!!
  elseif msg == "wantwrite" then
    socket.select(nil, {conn})        --> select for writing!!
  else
    -- other errors
  end
end
````

This is straightforward, it says "wait to become readable on `wantread`", and vice versa for write. 

The logic from the wiki text, is giving me strange problems with async connections (applying the same logic to `receive` and `send` timeouts). So is this wrong? and should I follow the logic from the example?

**Comment by Tieske** [comment]
Reversing the logic (do ignore the wiki text, and following the sample code) resolved the issues.

The weird part being that it actually worked the wrong way around. Except sending chunks, which was the weird part.

**Comment by daurnimator** [comment]
> The weird part being that it actually worked the wrong way around. Except sending chunks, which was the weird part.

Reversing it would:
  - wait for writability when you need readability (sockets are usually writable, so select will return immediately, but then you will block in `recv` (or end up looping if you have a timeout)
  - wait for readability when you need writability (and hence nothing will be sent until a byte is received)

**Comment by Tieske** [comment]
I tried updating the wiki, but didn't manage. So closing this now.
