### ISSUE TITLE
Add support for new curve selection API in OpenSSL

### ISSUE THREAD

**Issue by mwild1** [brunoos/luasec#42]
Currently LuaSec only allows you to select a single curve for ECDH, due to the limitations of the OpenSSL API.

OpenSSL 1.0.2 (released 22 Jan 2015) added a bunch of new functions for managing what curves are used: https://www.openssl.org/docs/ssl/SSL_CTX_set1_curves.html

At a minimum we should call SSL_CTX_set_ecdh_auto().

**Comment by wmark** [comment]
Addressed in PR #47 I hope. Please drop me a line if that is not what you expected or if does not compile with OpenSSL.
