### ISSUE TITLE
Is release 0.5 compatible with Lua 5.3?

### ISSUE THREAD

**Issue by J-Shep** [brunoos/luasec#45]
Hi,

If not, could there be a Lua 5.3 release in the not too distant future? I've read that the trunk code seems to be compatible with Lua 5.3.

**Comment by anatol** [comment]
I believe this change makes it 5.3 compatible https://github.com/brunoos/luasec/commit/9cb5220759aabedc0b4639c1a169b9efc5994a57

As 0.5 is too old I would vote for a new release that will be compatible with lua-5.3.

**Comment by J-Shep** [comment]
>> I believe this change makes it 5.3 compatible 9cb5220

@anatol Thanks for posting this info.

**Comment by brunoos** [comment]
Alpha version is compatible.
