### ISSUE TITLE
Error loading module ssl.core

### ISSUE THREAD

**Issue by is73** [brunoos/luasec#67]
I compiled luasec 0.6alpha-2 with openssl 1.0.2f using luarocks and compilation was succesfull.
I tried also 1.0.1r and 1.0.1e with no luck.

After requiring it using
`local https = require('ssl.https')`
I'm getting error

```
lua: error loading module 'ssl.core' from file 'c:\work\apps\lua\bin\..\lib\lua\5.3\ssl.dll':
	The specified module could not be found.


stack traceback:
	[C]: in ?
	[C]: in function 'require'
	c:\work\apps\lua\bin\..\share\lua\5.3\ssl.lua:7: in main chunk
	[C]: in function 'require'
	c:\work\apps\lua\bin\..\share\lua\5.3\ssl\https.lua:10: in main chunk
	[C]: in function 'require'
	C:\work\lua\test.lua:4: in main chunk
	[C]: in ?
[Finished in 0.1s]
```

OS win10
mingw32
cmake 3.4.3
lua 5.3.2
luarocks 2.3.0

ssl.dll looks pretty small ... 107kb

Please could you help me?

**Comment by pkulchenko** [comment]
@is73, I compiled luasec using the same version of OpenSSL and luasec and don't get any failures (I'm using my own build scripts). The size of ssl.dll looks correct (mine is 47kb, probably stripped); the error you are getting may indicate that ssl.dll didn't find `libeay32.dll` and `ssleay32.dll` libraries it needs (those come from OpenSSL), so you need to check if those are present and available in one of directories in `PATH`.

**Comment by is73** [comment]
Thank you very much! libeay32.dll and ssleay32.dll were in my LUA_CPATH not in PATH :) Request works.

Now I'm getting error "wrong version number" as code from https request, but this is may be problem of openssl itself.

**Comment by brunoos** [comment]
Probably it is the problem with redirect. Use redirect = false in https request.

**Comment by nodecentral** [comment]
Hi,

I have a lightly different error message, should I add it here, or create a new issue? (If I don’t hear back I’ll create a new ticker) thanks..

**Comment by brunoos** [comment]
You can send it here.
