### ISSUE TITLE
Build Issues in VS 2015?

### ISSUE THREAD

**Issue by scyto** [brunoos/luasec#71]
Hi, not a dev, but can poke.
I am having build issues - first wa build failure as /opensll/sll.h was missing along with ./lua.h and ./luaconf.h

Once i found these I got the project to start building but hit 91 errors and 25 warnings.

Should this build in VS 2015?

alex

**Comment by greatwolf** [comment]
You should probably post what some of those errors are. Many of them are likely cascading errors so you don't need to post the entire thing.

**Comment by brunoos** [comment]
I tested with 0.7alpha and it worked. You should install lua and openssl in your system and then configure the VC project accordingly.
