### ISSUE TITLE
Is 0.6 compatible with LuaJIT 2.0.4?

### ISSUE THREAD

**Issue by jirutka** [brunoos/luasec#78]
> Lua 5.2 and 5.3 compatibility

LuaJIT is compatible with Lua 5.1, so does LuaSec works on LuaJIT?

**Comment by pkulchenko** [comment]
I use luasec (0.6) with LuaJIT 2.0.4 (on Windows/OSX/Linux) and haven't seen any issues so far.

**Comment by brunoos** [comment]
Would be better to create a discussion list for luasec to avoid people to create this kind of issue?

**Comment by daurnimator** [comment]
I think there is an actual issue here: the README does not mention 5.1 compatibility.

**Comment by jirutka** [comment]
> Would be better to create a discussion list for luasec to avoid people to create this kind of issue?

No, it would be better to explicitly state in the readme if LuaSec is compatible with LuaJIT… And ideally add tests and run them on CI against supported Lua implementations.

**Comment by brunoos** [comment]
First, yes, readme is wrong...

My point is: since there is no discussion list, issue track has been used as a workaround.
For me, an issues should be created **after** a problem was detected.

**Comment by brunoos** [comment]
Closing, since luasec is compatible with luajit.

**Comment by jirutka** [comment]
But it’s still not stated in the README or anywhere else.

**Comment by brunoos** [comment]
It will be...
