### ISSUE TITLE
Issuing HTTPS request with POST method

### ISSUE THREAD

**Issue by alefebvre-ls** [brunoos/luasec#83]
I can't seem to figure out how to issue an POST request with the HTTPS library.  Would be nice to have this documented somewhere.

**Comment by daurnimator** [comment]
The API is the same as luasocket's `http.request` function. Please refer to the documentation there. http://w3.impa.br/~diego/software/luasocket/http.html

**Comment by alefebvre-ls** [comment]
Great, thanks for the info.
