### ISSUE TITLE
Server hangs / never receives on client requests

### ISSUE THREAD

**Issue by oyvindi** [brunoos/luasec#87]
Most, or all, of the samples in the repo seems to be based on that the server sends something to the client first on connection.

In my case, I initiate a server, and wait for the client to send a request. However, the server seems to hang on peer:receive(), until I kill the client. On the other hand, if I send something from the server first, the client receives it.

My client code is written in C#, while my server code basically looks like this. Certs + handshake etc works just fine, until peer:receive() hangs.

```
local socket = require("socket")
local ssl    = require("ssl")

local params = {
   mode = "server",
   protocol = "tlsv1_2",
   key = "C:\\ .... \\serverkey.pem",
   certificate  = "C:\\ .... \\server.pem",
   cafile = "C:\\ .... \\root.pem",
   verify = {"peer", "fail_if_no_peer_cert"},
   options = "all",
}

local server = socket.tcp()
local ctx = assert(ssl.newcontext(params))
server:setoption('reuseaddr', true)
assert( server:bind("10.20.2.92", 2000) )
server:listen()

local peer = server:accept()
peer = assert( ssl.wrap(peer, ctx) )
peer:dohandshake()
data = peer:receive()
print("receieved: " .. data)
peer:send("Pong!\n")
peer:close()
```

**Comment by brunoos** [comment]
If you can communicate from the server to the client, I don't think it is a SSL/TLS problem.
How many data do you send from the client?
Is TCP buffering it? (try to set tcp_nodelay on client)

**Comment by oyvindi** [comment]
Turns out the issue was on the other end, everything works as expected now. Sorry / thanks ! :)
