### ISSUE TITLE
Discourage the use of uncommon curves

### ISSUE THREAD

**Issue by wmark** [brunoos/luasec#98]
Luasec comes with a broad array configurable curves, of which some are not recommended, and some even deemed not secure for use in TLS.

I'd like to file a PR which will remove aliases for all but the most common and uncontested ones.

Unfortunately, given the widespread cargo-cult, relying on some "traditional" "magic" lists — near-constant lists like Mozilla's for cipher suites — would be the IMHO dangerous alternative. If we trimmed the list down then at least at some point installations which rely on obsolete recommendations would need to be revisited by their operator, which seldom happens in the wild. On the other hand, if someone were to insist on using `secp256k1` (don't) for TLS, he/she can easily amend the list.

**Comment by lanodan** [comment]
I think this is not the job of LuaSec but of the TLS(/SSL) library it’s linked to, for example SSLv3 is dangerous and it got removed from LibreSSL and OpenSSL.

**Comment by brunoos** [comment]
I understand the problem, but I will live it to user.
